# theme: "starter-hugo-academic"
# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Kostiantyn Ovsiannikov # Website name
baseurl: 'https://socinv.herokuapp.com/' # Website URL
copyright: 'Kostiantyn Ovsiannikov &#169; <script>document.write(new Date().getFullYear())</script>' # Footer text, e.g. '© {year} Me'

############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true


# Security
# https://stackoverflow.com/questions/70429317/blogdownserve-site-fails-to-produce-template-site
