[build]
  command = "npm run build"
  publish = "public"

[[plugins]]
  package = "@netlify/plugin-nextjs"
  
[context.production.environment]
  PYTHON_VERSION = "3.8"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200